name: Frontend Tests

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        working-directory: frontend
        run: npm install 

      - name: Test Build frontend
        run: npm run build 

      - name: Test Run frontend
        run: npm run start

      - name: Cleanup
        run: npm run stop
