name: Frontend Tests

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install --prefix frontend

      - name: Test Build frontend
        run: npm run build --prefix frontend

      - name: Test Run frontend
        run: npm run start --prefix frontend

      - name: Cleanup
        run: npm run stop --prefix frontend
